name: Auto Check Solution

on:
  pull_request:
    branches: [main]

jobs:
    create-pull-requst:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: main
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
            architecture: 'x64'
        - name: Setup Python Package
          run: |
            python -m pip install --upgrade pip
            pip install bs4 requests
        - name: Check Solution Language
          run: |
            python scripts/check_pull_request.py --pr_number ${{ github.event.number }} --check_language
        - name: setting label
          run: |
            echo "SOLUTION_LANG=`head -1 label`" >> $GITHUB_ENV
        - name: add Label
          if: contains(github.event.pull_request.labels.*.name, 'Solution') == false
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const { SOLUTION_LANG } = process.env
              github.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: [SOLUTION_LANG, "Solution"]
              })
        - name: Check Solution
          run: |
            python scripts/check_pull_request.py --pr_number ${{ github.event.number }}
